package com.gecko.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Gecko palette — monochrome black/white with true-neutral grays. No hue anywhere in the
// neutral scale, so nothing can fall back to Material's default purple-tinted baseline.
// Accent is ink-black on light, near-white on dark.

internal val GeckoDarkPrimary = Color(0xFFF2F2F2)
internal val GeckoDarkOnPrimary = Color(0xFF141414)
internal val GeckoDarkPrimaryContainer = Color(0xFF2C2C2C)
internal val GeckoDarkOnPrimaryContainer = Color(0xFFF2F2F2)
internal val GeckoDarkInversePrimary = Color(0xFF3D3D3D)
internal val GeckoDarkSecondary = Color(0xFFA8A8A8)
internal val GeckoDarkOnSecondary = Color(0xFF1A1A1A)
internal val GeckoDarkSecondaryContainer = Color(0xFF2C2C2C)
internal val GeckoDarkOnSecondaryContainer = Color(0xFFF2F2F2)
internal val GeckoDarkTertiary = Color(0xFFC2C2C2)
internal val GeckoDarkOnTertiary = Color(0xFF1A1A1A)
internal val GeckoDarkTertiaryContainer = Color(0xFF333333)
internal val GeckoDarkOnTertiaryContainer = Color(0xFFEDEDED)
internal val GeckoDarkBackground = Color(0xFF0B0B0B)
internal val GeckoDarkOnBackground = Color(0xFFEDEDED)
internal val GeckoDarkSurface = Color(0xFF141414)
internal val GeckoDarkOnSurface = Color(0xFFEDEDED)
internal val GeckoDarkSurfaceVariant = Color(0xFF232323)
internal val GeckoDarkOnSurfaceVariant = Color(0xFFA8A8A8)
internal val GeckoDarkInverseSurface = Color(0xFFEDEDED)
internal val GeckoDarkInverseOnSurface = Color(0xFF1A1A1A)
internal val GeckoDarkOutline = Color(0xFF3D3D3D)
internal val GeckoDarkOutlineVariant = Color(0xFF2A2A2A)
internal val GeckoDarkError = Color(0xFFFF6B6B)
internal val GeckoDarkOnError = Color(0xFF3B0A0A)
internal val GeckoDarkErrorContainer = Color(0xFF93000A)
internal val GeckoDarkOnErrorContainer = Color(0xFFFFDAD6)
internal val GeckoDarkScrim = Color(0xFF000000)
internal val GeckoDarkSurfaceContainer = Color(0xFF1A1A1A)
internal val GeckoDarkSurfaceContainerLow = Color(0xFF141414)
internal val GeckoDarkSurfaceContainerLowest = Color(0xFF0B0B0B)
internal val GeckoDarkSurfaceContainerHigh = Color(0xFF242424)
internal val GeckoDarkSurfaceContainerHighest = Color(0xFF2E2E2E)
internal val GeckoDarkSurfaceBright = Color(0xFF3A3A3A)
internal val GeckoDarkSurfaceDim = Color(0xFF0B0B0B)

internal val GeckoLightPrimary = Color(0xFF141414)
internal val GeckoLightOnPrimary = Color(0xFFFFFFFF)
internal val GeckoLightPrimaryContainer = Color(0xFFE9E9E9)
internal val GeckoLightOnPrimaryContainer = Color(0xFF141414)
internal val GeckoLightInversePrimary = Color(0xFFCFCFCF)
internal val GeckoLightSecondary = Color(0xFF5C5C5C)
internal val GeckoLightOnSecondary = Color(0xFFFFFFFF)
internal val GeckoLightSecondaryContainer = Color(0xFFE3E3E3)
internal val GeckoLightOnSecondaryContainer = Color(0xFF141414)
internal val GeckoLightTertiary = Color(0xFF3D3D3D)
internal val GeckoLightOnTertiary = Color(0xFFFFFFFF)
internal val GeckoLightTertiaryContainer = Color(0xFFDCDCDC)
internal val GeckoLightOnTertiaryContainer = Color(0xFF141414)
internal val GeckoLightBackground = Color(0xFFFCFCFC)
internal val GeckoLightOnBackground = Color(0xFF141414)
internal val GeckoLightSurface = Color(0xFFFFFFFF)
internal val GeckoLightOnSurface = Color(0xFF141414)
internal val GeckoLightSurfaceVariant = Color(0xFFF0F0F0)
internal val GeckoLightOnSurfaceVariant = Color(0xFF5C5C5C)
internal val GeckoLightInverseSurface = Color(0xFF2B2B2B)
internal val GeckoLightInverseOnSurface = Color(0xFFF2F2F2)
internal val GeckoLightOutline = Color(0xFFB8B8B8)
internal val GeckoLightOutlineVariant = Color(0xFFE0E0E0)
internal val GeckoLightError = Color(0xFFBA1A1A)
internal val GeckoLightOnError = Color(0xFFFFFFFF)
internal val GeckoLightErrorContainer = Color(0xFFFFDAD6)
internal val GeckoLightOnErrorContainer = Color(0xFF410002)
internal val GeckoLightScrim = Color(0xFF000000)
internal val GeckoLightSurfaceContainer = Color(0xFFF5F5F5)
internal val GeckoLightSurfaceContainerLow = Color(0xFFF8F8F8)
internal val GeckoLightSurfaceContainerLowest = Color(0xFFFFFFFF)
internal val GeckoLightSurfaceContainerHigh = Color(0xFFEDEDED)
internal val GeckoLightSurfaceContainerHighest = Color(0xFFE6E6E6)
internal val GeckoLightSurfaceBright = Color(0xFFFFFFFF)
internal val GeckoLightSurfaceDim = Color(0xFFDEDEDE)
